field: 3288ae42-571c-4b55-82a6-f69dfe49ac1c # Chapter
fieldLayouts:
  ea0c0e52-990f-466c-a7d6-b20d9047e827:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7b0b0dea-ad1b-430c-8b34-26eb35a6bc3e # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2814198-23b9-4ace-b62c-9ce02d13b203
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42131e96-8e9a-45c7-aaf9-da164e9a0410 # Start Time
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0faca27-29af-4056-8afe-909df3030138
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85cbd451-dfa3-4cee-881b-e5a83fa2cb10 # End Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e7c0b9e-f6a4-4b78-a811-9cfc56ab6da2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2c991e6b-4205-4641-a046-9f9ef8393bd8 # Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d22cc5bd-3327-4c26-8487-3b88090b998b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a9311ef-f9a0-4c8e-9130-a1f1f949742c # Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29549913-bbcd-41f5-af3e-e7febe8cebc6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c81df543-b448-4c37-9dab-8f99b2e46845 # toc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a47b716-095a-433a-a8c7-903c684af209
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33e66496-aebb-4d0e-9727-5925f354cea3 # Recipient
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7a8501e-2380-4ef1-88e5-6870ef3f8500
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 748248e8-64ba-4280-8a35-dd23340e2605 # Remote Percentage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ebfd9df-e160-463f-9c9f-fc1b3e54624a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: af376680-6dab-4260-8d78-6a0cd4a714df # Remote Start Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b4a2f70-c6f7-41d1-96b9-e08575fe86c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 45309bce-c074-4b82-a2ab-af27678c9a43 # Remote Item
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f015d39-b269-4042-af3f-9fbf00ea72bd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0c4a3b7d-d219-4d79-a995-9932daffffdd
        userCondition: null
fields:
  2c991e6b-4205-4641-a046-9f9ef8393bd8: # Url
    columnSuffix: heucqbjd
    contentColumnType: string(255)
    fieldGroup: null
    handle: chapterUrl
    instructions: null
    name: Url
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  7b0b0dea-ad1b-430c-8b34-26eb35a6bc3e: # Title
    columnSuffix: ayaghkcz
    contentColumnType: text
    fieldGroup: null
    handle: chapterTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8a9311ef-f9a0-4c8e-9130-a1f1f949742c: # Location
    columnSuffix: rlnsrykx
    contentColumnType: text
    fieldGroup: null
    handle: location
    instructions: null
    name: Location
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Name
                -
                  - handle
                  - name
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Latitude
                -
                  - handle
                  - lat
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - Longitude
                -
                  - handle
                  - lon
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col4
            -
              __assoc__:
                -
                  - heading
                  - OSM
                -
                  - handle
                  - osm
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
            -
              - col3
              - ''
            -
              - col4
              - ''
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  33e66496-aebb-4d0e-9727-5925f354cea3: # Recipient
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: recipient
    instructions: null
    name: Recipient
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 379973305
      columns:
        __assoc__:
          -
            - 89d3da74-aa15-436e-95ff-7a5ef45464c8 # Users
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 3dd38ac1-b8de-4d15-8f17-4a6eefaf2364 # Other Persons
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 7baf848c-4182-4d67-8b11-d030976a3ead # Split
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 6ea168eb-2cb8-4cd2-b574-dcf8a0b807b3 # Fee
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_5_recipient}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  85cbd451-dfa3-4cee-881b-e5a83fa2cb10: # End Time
    columnSuffix: ujrfihnf
    contentColumnType: text
    fieldGroup: null
    handle: endTime
    instructions: null
    name: 'End Time'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  42131e96-8e9a-45c7-aaf9-da164e9a0410: # Start Time
    columnSuffix: mtmjttid
    contentColumnType: text
    fieldGroup: null
    handle: startTime
    instructions: null
    name: 'Start Time'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  45309bce-c074-4b82-a2ab-af27678c9a43: # Remote Item
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: remoteItem
    instructions: null
    name: 'Remote Item'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:c0a47490-22dd-4c4b-b435-49aab2a77787' # Remote Items
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  748248e8-64ba-4280-8a35-dd23340e2605: # Remote Percentage
    columnSuffix: cdzhngxk
    contentColumnType: integer(10)
    fieldGroup: null
    handle: remotePercentage
    instructions: null
    name: 'Remote Percentage'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  af376680-6dab-4260-8d78-6a0cd4a714df: # Remote Start Time
    columnSuffix: ckhlshnv
    contentColumnType: integer(10)
    fieldGroup: null
    handle: remoteStartTime
    instructions: null
    name: 'Remote Start Time'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  c81df543-b448-4c37-9dab-8f99b2e46845: # toc
    columnSuffix: axnedpxj
    contentColumnType: boolean
    fieldGroup: null
    handle: toc
    instructions: null
    name: toc
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: chapter
name: Chapter
sortOrder: 1
