field: db56f6fb-8093-4d41-bef2-1ebbbdfbc997 # Recipient
fieldLayouts:
  1b997b20-1b11-4b7a-acd9-ac884545d765:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 11328a2a-4790-4ab3-83ad-35b165d6baed # Registered users
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fc53891-4e08-4ae0-bfe8-6dde1d1ccf9f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 631e6bb4-059f-4224-a778-4d10920e565d # Other Recipients
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e990bf7-7c7a-41cc-a7c1-2d0286708ec2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4ae34e8c-9560-4c37-a23c-84bb868420e3 # Split
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e2cce9b-ff1a-41fb-8784-ccec09f26faa
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ed2e10f8-6e42-46eb-b9fb-f0f10a110d00 # Fee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5daa4e42-a35e-41eb-a3a1-b11d02b06e8b
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 057b659d-aa5d-4313-9cef-d042c228bc85
        userCondition: null
fields:
  4ae34e8c-9560-4c37-a23c-84bb868420e3: # Split
    columnSuffix: tajbuvdy
    contentColumnType: integer(10)
    fieldGroup: null
    handle: split
    instructions: null
    name: Split
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  631e6bb4-059f-4224-a778-4d10920e565d: # Other Recipients
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entryRecipient
    instructions: null
    name: 'Other Recipients'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:c935f29c-7efb-4f69-991b-b479f7bcdd45' # Persons
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  11328a2a-4790-4ab3-83ad-35b165d6baed: # Registered users
    columnSuffix: zjfrmejr
    contentColumnType: string
    fieldGroup: null
    handle: userRecipient
    instructions: null
    name: 'Registered users'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\User
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\users\UserCondition
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Users
  ed2e10f8-6e42-46eb-b9fb-f0f10a110d00: # Fee
    columnSuffix: tappgnsj
    contentColumnType: boolean
    fieldGroup: null
    handle: fee
    instructions: null
    name: Fee
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: recipient
name: Recipient
sortOrder: 1
