field: c5a173d0-a09a-4a3d-adee-04666b45a6ab # Soundbite
fieldLayouts:
  09f97f49-fb80-414a-80ee-deead656faac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5e327d1f-cce6-4c06-9b06-bc8cbbe944f5 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 935cf526-362d-469b-a0fe-aa6a79116757
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac32e1ab-c183-412e-8f08-e1a340fd538d # Start Time
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98fc063f-6766-4485-8e5c-7c294a16fa28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05ba8848-0f41-4de5-a53f-1c843fdbf263 # Duration
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d36b558b-6ebc-4e0f-9c21-b9a1c1ee82e7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7710fe88-2917-45c9-a6c3-52cb501751c4 # Recipient
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca552722-b3fd-466f-97f1-a3c793bfff65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a97c03ae-5ee7-48f6-813d-886a825b1e6a # Remote Percentage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9747ddc0-f6d7-454d-b59a-f954c111eaf0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 517a8c0c-fce5-4dd3-bccd-fe3aaa54abde # Remote Start Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73275d56-b834-4781-8cac-dda0541cfa56
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9dd3f69f-ccd0-431c-b8b0-99ce19f8f830 # Remote Item
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d86cc5ae-fb0a-45d1-bb23-b9d100639c28
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b490df7-6586-419e-8bd0-4975d7dc47d8
        userCondition: null
fields:
  05ba8848-0f41-4de5-a53f-1c843fdbf263: # Duration
    columnSuffix: rpqmokzk
    contentColumnType: text
    fieldGroup: null
    handle: duration
    instructions: null
    name: Duration
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5e327d1f-cce6-4c06-9b06-bc8cbbe944f5: # Title
    columnSuffix: uslppxnj
    contentColumnType: text
    fieldGroup: null
    handle: soundbiteTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9dd3f69f-ccd0-431c-b8b0-99ce19f8f830: # Remote Item
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: remoteItem
    instructions: null
    name: 'Remote Item'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:c0a47490-22dd-4c4b-b435-49aab2a77787' # Remote Items
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  517a8c0c-fce5-4dd3-bccd-fe3aaa54abde: # Remote Start Time
    columnSuffix: gygdsduf
    contentColumnType: integer(10)
    fieldGroup: null
    handle: remoteStartTime
    instructions: null
    name: 'Remote Start Time'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  7710fe88-2917-45c9-a6c3-52cb501751c4: # Recipient
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: recipient
    instructions: null
    name: Recipient
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1471351352
      columns:
        __assoc__:
          -
            - 9d8a9d4b-c7c4-44fa-a9e2-a004907548ce # Users
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 68bedd35-2c4e-481f-bbf3-89051641327c # Other Persons
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 03ac74e5-a3e7-4c60-9956-3ba1b80dd959 # Split
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 63394233-4f95-4558-ac66-4ab95a91c1d5 # Fee
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_4_recipient}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  a97c03ae-5ee7-48f6-813d-886a825b1e6a: # Remote Percentage
    columnSuffix: alwxvfxz
    contentColumnType: integer(10)
    fieldGroup: null
    handle: remotePercentage
    instructions: null
    name: 'Remote Percentage'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  ac32e1ab-c183-412e-8f08-e1a340fd538d: # Start Time
    columnSuffix: mtwcfvip
    contentColumnType: text
    fieldGroup: null
    handle: startTime
    instructions: null
    name: 'Start Time'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: soundbite
name: Soundbite
sortOrder: 1
