color: null
fieldLayouts:
  ce3200dd-88ec-42a6-9936-956f12e146e9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 423246d7-2ca3-440b-b873-b05a23df015d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e10ad14a-df74-4754-a499-ddefbf048ef3 # Enclosure Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44b5ebe9-e751-4216-bbd9-026a1909c8be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 58ce6e02-4a1f-4afe-b611-c9c56a82fc26 # Enclosure Type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37dbfa9d-568f-4d1f-a08c-7f7d8cc05066
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dde88f6e-5bea-4f1b-9ef4-914d49674f23 # Enclosure Bitrate
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8a0ba6e-e0f9-42df-9d34-ea0147c41234
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5dde8c25-54f5-4210-b8be-e605ddcd93db # Asset Sources
            handle: null
            includeInCards: false
            instructions: null
            label: 'Asset Sources'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8241f932-bf52-400b-b0a0-c1eb6dba9e77
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 68604891-1c15-4388-8882-7fdb3030577f # Other Sources
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7416259-57b4-43ce-bc48-e336e4cd5a50
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 13a9cf2e-9fb9-4873-b054-40589944a9c0 # Enclosure Rel
            handle: null
            includeInCards: false
            instructions: null
            label: 'Enclosure Rel'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e22d54e-6999-45be-b57e-76daf7aef38f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f19c16d-651f-4cbd-90c4-1c6949340bb1 # Enclosure Default
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7066903-a99a-4762-bdb5-e100701d58a5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 242c9898-d7ba-4e68-b8b0-227b81c90636
        userCondition: null
handle: alternateEnclosure
hasTitleField: false
icon: ''
name: 'Alternate Enclosure'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
