fieldLayouts:
  7b64f00f-9b67-49b5-835b-23235ae91df4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7a6a298e-5424-447b-9d53-ef25cccf4953
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 220e1759-47ff-4b8b-a93f-08466673270a # Person Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20694c71-4d49-4826-8c3b-44931908cea5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3fdc58af-9dca-4f46-b2ed-ef35841da1c8 # Person Picture
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8293ea44-e1fc-4f47-9cfa-df9a3ff64cb9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1033a0ba-39af-48f2-b6d2-4ca0d28cadb9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1432412f-9c0d-43ac-88b7-857eecc63f61 # Recipient Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac8cbc42-b4f1-434b-8ca8-6d4d644bddc7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 136734f5-c727-4e51-974b-356d424546c8 # Recipient Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7f1b9d4-0056-48c8-bebf-7f89314e8bca
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1332b520-87b6-420f-81c3-d48ea863d387 # Recipient Custom Key
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7627424-b61f-4f52-b3b2-76db96bf4135
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e03aaa4f-be84-4c30-a472-d8d0ced40b93 # Recipient Custom Value
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 324c7e0b-7c76-435b-aec9-912558531c7a
            userCondition: null
            warning: null
            width: 50
        name: 'Recipient Information'
        uid: 2e64aabd-7c1c-4a6a-813b-222794957032
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: c935f29c-7efb-4f69-991b-b479f7bcdd45 # Persons
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
