fieldLayouts:
  ac5b3fa0-4dc7-4f7d-8753-298ecd964e14:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9b9d15e6-5b89-423a-a281-e0bb1140dda9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f7b437a-417a-40f1-a8ec-fcbd88293424 # Live Item Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cd4f775-e5db-481b-93df-9734995cfe96
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 95394800-44fd-49cc-bbb4-27033deea0a5 # Live Author
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f5dd5c3-a895-4964-af93-80b7a59c1329
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5925a0d1-08a6-4bca-806f-50dbeef6a2e6 # GUID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 817647e1-dd3b-4dc9-8754-fcd37042b359
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61290fb0-f9fd-4170-be33-fbb08d60a985 # Explicit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efa7b0fc-1551-439d-a969-abd59b4e5238
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ca75481f-e1fc-46c8-8184-72633d1fd5ea # Live Status
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0dc347b9-01ee-4d61-a283-19bc83cfc5d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2364fcc8-9f40-4c69-9958-e1675130fc89 # Live Start Date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5463486b-c6c9-48a4-88e2-66643c996cef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6a3549cb-244a-46ff-bf09-6df38a74c997 # Live End Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1caad0e-bb11-4de6-bba0-cc34c4721c37
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 47a058e2-4241-4b6a-aa43-05e9b12f5ea0 # Live Enclosure
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e2d128a-93a2-4d2c-a85d-0029679f9818
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 00d61740-e612-471f-bc8e-1e4daedb60be # Live Alternate Enclosure
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1d482c6-b0d0-46bf-8611-1f6d8fed1dd0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04432943-c8c1-4bda-9291-86bb63d85747 # Content Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7221976b-0ccc-4fff-a083-c8a8663b05f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7482f214-925d-4db3-8407-910054af3909 # Person
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d0006bc-c822-4722-b504-438ae1b0348e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2640a2c4-dbd1-4c8a-a10c-1a134d70b2af
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 0a4f8c97-65cd-45e5-ad4b-b530b1504fa6 # Live Items
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
