color: null
fieldLayouts:
  433b5866-32db-4ccc-8e81-ae1be7159e39:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 15b69396-325c-4f70-83ca-16868906813f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: db1e3c64-a981-480a-aa75-5d633df51b68
        userCondition: null
handle: podcastCategories
hasTitleField: true
icon: ''
name: 'Podcast Categories'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
