color: null
fieldLayouts:
  1b997b20-1b11-4b7a-acd9-ac884545d765:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4c8244c9-caf5-4559-85ab-d3831cc278b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 11328a2a-4790-4ab3-83ad-35b165d6baed # User Recipient
            handle: null
            includeInCards: true
            instructions: null
            label: Users
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fc53891-4e08-4ae0-bfe8-6dde1d1ccf9f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 631e6bb4-059f-4224-a778-4d10920e565d # Entry Recipients
            handle: null
            includeInCards: false
            instructions: null
            label: 'Other Recipients'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e990bf7-7c7a-41cc-a7c1-2d0286708ec2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4ae34e8c-9560-4c37-a23c-84bb868420e3 # Split
            handle: null
            includeInCards: false
            instructions: null
            label: Split
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e2cce9b-ff1a-41fb-8784-ccec09f26faa
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ed2e10f8-6e42-46eb-b9fb-f0f10a110d00 # Fee
            handle: null
            includeInCards: false
            instructions: null
            label: Fee
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5daa4e42-a35e-41eb-a3a1-b11d02b06e8b
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 057b659d-aa5d-4313-9cef-d042c228bc85
        userCondition: null
handle: recipient
hasTitleField: false
icon: ''
name: Recipient
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
