fieldLayouts:
  5f726aaf-f246-4a7e-b552-c865b231ee70:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 44644216-f325-4a92-8453-b1893b853cbe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 386da6f6-c7a5-4c44-84be-dbab07bb7b6a
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
