fieldLayouts:
  16ebf9ec-0104-4012-bced-719e844c35e7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e3ac6a0a-f305-4452-ae4e-87ac9bf141fb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c6927d89-c939-49ed-a380-55e218217e47
        userCondition: null
fs: mainAsset
handle: mainAsset
name: 'Main Asset'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
