fieldLayouts:
  6af2d5d7-f12f-404f-ba9a-470091a9fca4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f1f87322-3533-4b3f-a918-0b2039881284
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 75ea975e-0617-43dd-ad08-ffa36d32205e # Publish Date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f744b30-ef91-432c-9ee1-cbbcfc31e7d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8f965504-e3e9-4838-b185-ac7db7b4afd1 # Season
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd0d16a1-9928-4f69-b1d2-0f9115cb7708
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 98be61bd-7bd7-4bb0-9737-227797a50227
        userCondition: null
fs: trailer
handle: trailer
name: Trailer
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
