columnSuffix: heucqbjd
handle: chapterUrl
instructions: null
name: 'Chapter URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
