columnSuffix: iwbrvmyh
contentColumnType: text
handle: contentEncoded
instructions: null
name: 'Content Encoded'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 5b9bceab-0ffa-43e2-9b4c-b7834bbbe199 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
