columnSuffix: ktkhsagv
contentColumnType: text
handle: description
instructions: null
name: Description
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 5b9bceab-0ffa-43e2-9b4c-b7834bbbe199 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
