columnSuffix: tappgnsj
handle: fee
instructions: null
name: Fee
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
