columnSuffix: lappququ
contentColumnType: text
handle: itemGuid
instructions: null
name: 'Item Guid'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
