columnSuffix: odgnidar
contentColumnType: string
handle: liveStatus
instructions: null
name: 'Live Status'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Pending
        -
          - value
          - pending
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Live
        -
          - value
          - live
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Ended
        -
          - value
          - ended
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
