columnSuffix: null
contentColumnType: string
fieldGroup: eef5d741-f0d2-41f5-a2e7-4775a87c4004 # Common
handle: liveAlternateEnclosure
instructions: null
name: 'Live Alternate Enclosure'
searchable: false
settings:
  contentTable: '{{%matrixcontent_livealternateenclosure}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
