columnSuffix: fwrqwgny
handle: otherSources
instructions: null
name: 'Other Sources'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - uri
            -
              - handle
              - uri
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - contentType
            -
              - handle
              - contentType
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - 'Select one'
                    -
                      - value
                      - ''
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - application/x-bittorrent
                    -
                      - value
                      - application/x-bittorrent
                    -
                      - default
                      - false
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
