columnSuffix: oqvpsfsm
contentColumnType:
  - 'date:datetime'
  - 'tz:string'
fieldGroup: eef5d741-f0d2-41f5-a2e7-4775a87c4004 # Common
handle: pubdate
instructions: null
name: 'Publish Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: true
  showTimeZone: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
