columnSuffix: oeiswgze
contentColumnType: integer(10)
fieldGroup: eef5d741-f0d2-41f5-a2e7-4775a87c4004 # Common
handle: season
instructions: null
name: Season
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
