columnSuffix: tajbuvdy
handle: split
instructions: null
name: Split
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: null
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
