columnSuffix: topxccya
contentColumnType: string
handle: transcriptFormats
instructions: null
name: 'Transcript Formats'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - HTML
        -
          - value
          - html
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - JSON
        -
          - value
          - json
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - SRT
        -
          - value
          - srt
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - TEXT
        -
          - value
          - text
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - VTT
        -
          - value
          - vtt
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\MultiSelect
