columnSuffix: xjxaxbia
contentColumnType: text
fieldGroup: eef5d741-f0d2-41f5-a2e7-4775a87c4004 # Common
handle: transcript
instructions: null
name: 'Transcript Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
