columnSuffix: null
contentColumnType: string
fieldGroup: eef5d741-f0d2-41f5-a2e7-4775a87c4004 # Common
handle: value4value
instructions: null
name: 'Value 4 Value'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:0dd9378a-914f-49e5-bee2-b6a6b5e7ec79' # Value 4 Value
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
