columnSuffix: opzbplqc
contentColumnType: text
handle: valueSuggested
instructions: null
name: 'Suggested Value'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
