changedFieldIndicator: 741652339
field: 33e66496-aebb-4d0e-9727-5925f354cea3 # Recipient
fieldLayouts:
  bb8ef6f9-4cfd-4f10-b3a5-d29ead850316:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 89d3da74-aa15-436e-95ff-7a5ef45464c8 # Users
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f615edf0-de09-40c2-b8cc-623e69830dcc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3dd38ac1-b8de-4d15-8f17-4a6eefaf2364 # Other Persons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1d87886-d311-4275-9518-11194fe875bc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7baf848c-4182-4d67-8b11-d030976a3ead # Split
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f24286fe-c46f-4667-89cd-664fde36d83e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ea168eb-2cb8-4cd2-b574-dcf8a0b807b3 # Fee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44534de9-08c6-4148-ad07-32fc04775bdf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 44928e5c-e215-4fc1-8f71-f7fe9f3c0b77
        userCondition: null
fields:
  3dd38ac1-b8de-4d15-8f17-4a6eefaf2364: # Other Persons
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entryRecipient
    instructions: null
    name: 'Other Persons'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:c935f29c-7efb-4f69-991b-b479f7bcdd45' # Persons
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  6ea168eb-2cb8-4cd2-b574-dcf8a0b807b3: # Fee
    columnSuffix: nhdjqhbj
    contentColumnType: boolean
    fieldGroup: null
    handle: fee
    instructions: null
    name: Fee
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  7baf848c-4182-4d67-8b11-d030976a3ead: # Split
    columnSuffix: vyryrnad
    contentColumnType: integer(10)
    fieldGroup: null
    handle: split
    instructions: null
    name: Split
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  89d3da74-aa15-436e-95ff-7a5ef45464c8: # Users
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: userRecipient
    instructions: null
    name: Users
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\User
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\users\UserCondition
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Users
