changedFieldIndicator: 1233725812
field: 55274cf3-bcd0-49e3-a776-77478070fcb5 # Recipient
fieldLayouts:
  ee0e3f70-60b0-410f-808f-df081cf9c388:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0cd5fd98-4e7c-4cf4-9209-6e90766d9f7c # Users
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdc033c0-323c-4348-8912-dc83baad7341
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ab0ec966-4721-4ce3-a641-c7d45d3352fe # Other Persons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c743bb73-b0b6-4250-b12c-479cd7b51332
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8eb2c853-eb79-4f36-9236-1b21c9b03134 # Split
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e10c69d5-92b9-477d-8141-c868a68a0836
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e4b91f0e-a89c-46dd-9670-de79c7797c32 # Fee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 248e1d8d-270e-49db-b44b-f2d4443660a0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6ec97fab-f37f-4b6d-9516-4b00d2695739
        userCondition: null
fields:
  0cd5fd98-4e7c-4cf4-9209-6e90766d9f7c: # Users
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: userRecipient
    instructions: null
    name: Users
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\User
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\users\UserCondition
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Users
  8eb2c853-eb79-4f36-9236-1b21c9b03134: # Split
    columnSuffix: vhhrrpgy
    contentColumnType: integer(10)
    fieldGroup: null
    handle: split
    instructions: null
    name: Split
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  ab0ec966-4721-4ce3-a641-c7d45d3352fe: # Other Persons
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entryRecipient
    instructions: null
    name: 'Other Persons'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:c935f29c-7efb-4f69-991b-b479f7bcdd45' # Persons
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  e4b91f0e-a89c-46dd-9670-de79c7797c32: # Fee
    columnSuffix: qkcpsjkz
    contentColumnType: boolean
    fieldGroup: null
    handle: fee
    instructions: null
    name: Fee
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
