defaultPlacement: end
enableVersioning: false
handle: persons
name: Persons
propagationMethod: all
siteSettings:
  a250298a-1871-4e91-96cf-3071507954ad: # Default
    enabledByDefault: true
    hasUrls: true
    template: persons/_entry
    uriFormat: 'persons/{slug}'
type: channel
