defaultPlacement: end
enableVersioning: false
entryTypes:
  - b5d5877a-e3d6-4fd6-9182-eff3f0b24270 # Persons
handle: persons
maxAuthors: 1
name: Persons
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  a250298a-1871-4e91-96cf-3071507954ad: # Default
    enabledByDefault: true
    hasUrls: true
    template: persons/_entry
    uriFormat: 'persons/{slug}'
type: channel
