defaultPlacement: end
enableVersioning: true
entryTypes:
  - 46e47596-61fa-4375-8243-48ca211a4fdc # Podcast Taxonomies
handle: podcastTaxonomies
maxAuthors: 1
name: 'Podcast Taxonomies'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  a250298a-1871-4e91-96cf-3071507954ad: # Default
    enabledByDefault: true
    hasUrls: true
    template: podcast-taxonomy/_entry
    uriFormat: 'podcast-taxonomy/{slug}'
structure:
  maxLevels: null
  uid: 12af11c7-6091-4a2c-b9d7-1875a94104cb
type: structure
